#!/bin/bash

start_ip=$1
end_ip=$2
on_line_numbers=0
off_line_numbers=0

# make sure syntax sane
if [ $# -ne 2 ]; then
	echo "Usage: $0 start_ip end_ip"
	exit 1
fi

# empty file list
echo $(date)> /tmp/online.ip
echo "---------------------------------" >> /tmp/online.ip
echo $(date)> /tmp/offline.ip
echo "---------------------------------" >> /tmp/offline.ip

# check by ping ip
for i in `seq $start_ip $end_ip`; do
	if ping -w 1 -t 2 192.168.101.$i; then
		echo "192.168.101.$i" >> /tmp/online.ip
		let on_line_numbers++
	else
		echo "192.168.101.$i" >> /tmp/offline.ip
		let off_line_numbers++
	fi
done

# sum
echo "---------------------------------" >> /tmp/online.ip
echo "sum: $on_line_numbers" >> /tmp/online.ip
echo "---------------------------------" >> /tmp/offline.ip 
echo "sum: $off_line_numbers" >> /tmp/offline.ip
