#!/bin/bash

# chkconfig:   - 80 20
# description: startup script for svn on linux

SVN_REPO=/alidata/svnrepotest/
SVN_PORT=3690
. /etc/init.d/functionbyyang

check_status() {
    netstat -tlnp | grep ${SVN_PORT} &> /dev/null && return 0 || return 1 
}

start() {
    check_status
    if [ $? == 1 ]; then
#        echo -n "Starting SVN ... "
		if svnserve -d -r ${SVN_REPO}; then
			sleep 2
			success_state "Starting svn repo ${SVN_REPO}" 
		else
			failed_state "Starting svn repo ${SVN_REPO}"
		fi
    else
        echo "SVN ${SVN_REPO} is running."
    fi
}

stop() {
    check_status
    if [ $? == 0 ]; then
        if killall svnserve;then
			sleep 2
            success_state "Stop svn repo ${SVN_REPO}"
        else
            failed_state "Stop svn repo ${SVN_REPO}"
        fi
    else
        echo "SVN is not running."
    fi
}

status() {
    check_status
    if [ $? == 0 ]; then
        echo "SVN is running."
    else
        echo "SVN is stopped."
    fi
}


case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
		status
		;;
    restart)
        stop
        sleep 10
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
