#!/bin/bash
#
#
# chkconfig:   - 85 15
# description: The Script for SVN service
server_name=svnserve

# only need to modify this.
svnrepo=/alidata/svndata
start_server="svnserve -d -r $svnrepo"
stop_server="killall $server_name"

function check_status(){
	netstat -tlnp | grep -q "$server_name"
	if [ $? = 0 ];then
		echo "SVN $svnrepo is running..." && return 0
	else 
		echo "SVN $svnrepo is stpped" &&  return 1
	fi
}

function start(){
	check_status || $start_server && echo "start SVN $svnrepo OK"
}

function stop(){
	check_status && $stop_server  && echo "stop SVN $svnrepo OK"
}

function restart(){
	check_status
	if [ $? = 1 ];then
		$stop_server  && echo "stop SVN $svnrepo OK"
		$start_server && echo "start SVN $svnrepo OK"
	fi
}

case $1 in
	start)
		start;;
	stop)
		stop;;
	restart)
		restart;;
	status)
		check_status;;
	*)
		echo "sytax error"
	esac
