#!/bin/bash
#
# written by hiyang @ 2017-01-16

## search a string with specified suffix in configuration file in current directory
# $1 : string for search
# $2 : suffix
case $# in
	# only have string for search
	1)
	find ./ -type f | xargs file | awk -F : '/ASCII text$/ { print $1 }' | while read lines; do
	    if grep $1 $lines &> /dev/null; then
		      echo -e "\e[33m$lines\e[0m" && grep --color -n $1 $lines
	    fi
	done
	;;
	# have string for search and suffix of file
	2)
	find ./ -type f -name "*$2"| xargs file | awk -F : '/ASCII text$/ { print $1 }' | while read lines; do
	    if grep $1 $lines &> /dev/null; then
		      echo -e "\e[33m$lines\e[0m" && grep --color -n $1 $lines
	    fi
	done
	;;
	*)
	# illegal para
	echo "Something wrong!!!"
	echo "Usage: grept string [suffix]"
	;;
esac
