#!/bin/bash

# chkconfig:   - 80 20
# description: startup script for tomcat on linux
start_tomcat=$TOMCAT_HOME/bin/startup.sh
stop_tomcat=$TOMCAT_HOME/bin/shutdown.sh
JAVA_PORT=8081

start() {
    check_status
    if [ $? == 0 ]; then
        echo -n "Starting tomcat: "
        ${start_tomcat} && echo "tomcat start ok"
    else
        echo -n "tomcat is running"
    fi
}

stop() {
    check_status
    if [ $? == 1 ]; then
        echo -n "Shutdown tomcat"
        ${stop_tomcat} && echo "tomcat stop ok"
    else
        echo -n "tomcat is not running"
    fi
}

status() {
    check_status
    if [ $? == 1 ]; then
        echo -n "tomcat is running"
    else
        echo -n "tomcat is stopped"
    fi
}

check_status() {
    netstat -tlnp | grep ${JAVA_PORT} &> /dev/null && return 1 || return 0 
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
	status
	;;
    restart)
        stop
        sleep 10
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|status|restart}"
esac

exit 0
