#!/bin/bash
#
# svnserve        Startup script for the Subversion svnserve
#
# chkconfig: - 85 15
# description: The svnserve daemon allows access to Subversion repositories \
#              using the svn network protocol.

# Modify exe, prog, option
start_prog="/usr/local/apache-tomcat-8.5.4/bin/catalina.sh start"
stop_prog="/usr/local/apache-tomcat-8.5.4/bin/catalina.sh stop"
prog=tomcat
port=8080
#option="-d -r /data/svndata/"

delay_restart=5
lockfile=/var/lock/subsys/$prog

############################################################################################
start() {
    if check_status &> /dev/null; then
        echo "$prog is running... " && echo -e "Starting $prog: \t\t\e[31m[ failed ]\e[0m" && return 1
    else
        $start_prog $option && echo -e "Starting $prog: \t\t\e[32m[  OK  ]\e[0m" && touch $lockfile && return 0
    fi
}

stop() {
    if check_status &> /dev/null; then
        $stop_prog && rm -f $lockfile && echo -e "Stopping $prog: \t\t\e[32m[  OK  ]\e[0m" && return 0
    else
        echo "$prog is stopped." && echo -e "Stopping $prog: \t\t\e[31m[ failed ]\e[0m" && return 1
    fi   
}

pid() {
    pid=`netstat -tlnp | egrep "$port\>" | awk '{ print $NF }' | cut -d / -f1`
}

check_status() {
    netstat -tlnp | egrep "$port\>"
}

status() {
    echo "Proto Recv-Q Send-Q Local Address               Foreign Address             State       PID/Program name"
    check_status 2> /dev/null 
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        stop && sleep $delay_restart && start
        ;;
    status)
        status
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|restart}"
esac

